### ISSUE TITLE
Is it possible to successfully execute code in colab?

### ISSUE THREAD

**Issue by KirillKukharev** [jaketae/storyteller#15]
I've got an error  "The session has been terminated because the amount of RAM is completely exhausted." The same problem with GPU. 
Are there ways to optimize memory in Story Teller for colab?

**Comment by jaketae** [comment]
Hello @KirillKukharev, thanks for opening this issue. I've been meaning to create a Colab demo notebook but got carried away by other things.

One thing that immediately comes to mind is using [`accelerate`](https://huggingface.co/docs/accelerate/index). IIRC, simply `pip install accelerate` should make things better due to their default setting. However, your mileage may vary depending on the configuration and generation arguments.

Story Teller is already generating one image at a time instead of batching, so I would say that it is already erring on the side of being slow while saving on memory. I'm curious to see at which stage memory is running out (File I/O, image generation, TTS). Sorry that I don't have a definitive answer; please keep me posted if you have any updates, and I'll do the same. Thanks!
